import Link from 'next/link'
import '../globals.css'
import { getPages } from '@/sanity/sanity-utils';

export const metadata = {
  title: 'My Portofolio Site by Next + Sanity',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  //get all of our pages
  const pages = await getPages();


  return (
    <html lang="en">
      <body className='max-w-3xl mx-auto py-10'>
        {/* justify-between makes home to the left, contact and about to the right */}
        <header className='flex items-center justify-between'>
          <Link 
            href="/"
            className = "bg-gradient-to-r from-orange-400 via-red-500 to-purple-600 bg-clip-text text-transparent text-lg font-bold"
          >
            Home
          </Link>

          {/* add links for pages, href right after the homepage */}
          <div className='flex items-center gap-5 text-sm text-gray-600'>
            {pages.map((page) => (
              <Link 
                key={page._id} 
                href={`/${ page.slug }`} 
                className='hover:underline'
              >
                { page.title }
              </Link>
            ))}
          </div>
        </header>
        <main className='py-20'>{children}</main>
      </body>
    </html>
  )
}
